from Videonoleggio import *

m1: Movie = Movie("123", "Ciao", "Qualcuno")
# mErrore: Movie = Movie("123", "Ci", "ao")
m2: Movie = Movie("321", "aaa", "Persona")
m3: Movie = Movie("789", "Film Generico", "Qualcuno")
m4: Movie = Movie("987", "Muu", "Qualcun'altro")

print("\nNoleggio e restituzione film a nessuno")
print("Film noleggiato con successo." if m1.rent() == None else "")
m1.rent()
print("Film restituito con successo." if m1.return_movie() == None else "")
m1.return_movie()

c1: Customer = Customer("abc", "Cri")
# cErrore: Customer = Customer("abc", "ciao")
c2: Customer = Customer("cba", "Marcel")
c3: Customer = Customer("xyz", "Stefano")
c4: Customer = Customer("zyx", "Lorenzo")

print("\nNoleggio film a una persona")
print("\"Ciao\" è noleggiato." if m1.is_rented else "\"Ciao\" non è noleggiato")
print("Noleggiato il film con successo." if c1.rent_movie(m1) == None else "")
c1.rent_movie(m1)
print("\"Ciao\" è noleggiato." if m1.is_rented else "\"Ciao\" non è noleggiato")
c1.rent_movie(m1)
c1.rent_movie(m1)
c1.rent_movie(m1)
c1.rent_movie(m1)
print(c1.rented_movie)

print("\nRestituzione film a una persona")
print("\"Ciao\" è noleggiato." if m1.is_rented else "\"Ciao\" non è noleggiato")
print("Restituisco il film con successo." if c1.return_movie(m1) == None else "")
c1.return_movie(m1)
print("\"Ciao\" è noleggiato." if m1.is_rented else "\"Ciao\" non è noleggiato")
c1.return_movie(m1)
c1.return_movie(m1)
c1.return_movie(m1)
c1.return_movie(m1)
c1.return_movie(m1)
print(c1.rented_movie)

print()
vrs: VideoRentalStore = VideoRentalStore()